(in-package :gst)

(glib::at-init () (foreign-funcall "gst_message_get_type" :int))

(defconstant +gst-message-unknown+ (ash 0 0))
(defconstant +gst-message-eos+ (ash 1 0))
(defconstant +gst-message-error+ (ash 1 1))
(defconstant +gst-message-warning+ (ash 1 2))
(defconstant +gst-message-info+ (ash 1 3))
(defconstant +gst-message-tag+ (ash 1 4))
(defconstant +gst-message-buffering+ (ash 1 5))
(defconstant +gst-message-state-changed+ (ash 1 6))
(defconstant +gst-message-state-dirty+ (ash 1 7))
(defconstant +gst-message-step-done+ (ash 1 8))
(defconstant +gst-message-clock-provide+ (ash 1 9))
(defconstant +gst-message-clock-lost+ (ash 1 10))
(defconstant +gst-message-new-clock+ (ash 1 11))
(defconstant +gst-message-structure-change+ (ash 1 12))
(defconstant +gst-message-stream-status+ (ash 1 13))
(defconstant +gst-message-application+ (ash 1 14))
(defconstant +gst-message-element+ (ash 1 15))
(defconstant +gst-message-segment-start+ (ash 1 16))
(defconstant +gst-message-segment-done+ (ash 1 17))
(defconstant +gst-message-duration-changed+ (ash 1 18))
(defconstant +gst-message-latency+ (ash 1 19))
(defconstant +gst-message-async-start+ (ash 1 20))
(defconstant +gst-message-async-done+ (ash 1 21))
(defconstant +gst-message-request-state+ (ash 1 22))
(defconstant +gst-message-step-start+ (ash 1 23))
(defconstant +gst-message-qos+ (ash 1 24))
(defconstant +gst-message-progress+ (ash 1 25))
(defconstant +gst-message-toc+ (ash 1 26))
(defconstant +gst-message-reset-time+ (ash 1 27))
(defconstant +gst-message-stream-start+ (ash 1 28))
(defconstant +gst-message-need-context+ (ash 1 29))
(defconstant +gst-message-have-context+ (ash 1 30))
(defconstant +gst-message-extended+ (ash 1 31))
(defconstant +gst-message-device-added+ (+ +gst-message-extended+ 1))
(defconstant +gst-message-device-removed+ (+ +gst-message-extended+ 2))
(defconstant +gst-message-property-notify+ (+ +gst-message-extended+ 3))
(defconstant +gst-message-stream-collection+ (+ +gst-message-extended+ 4))
(defconstant +gst-message-streams-selected+ (+ +gst-message-extended+ 5))
(defconstant +gst-message-redirect+ (+ +gst-message-extended+ 6))
(defconstant +gst-message-any+ #xffffffff)

(define-g-boxed-cstruct gst-message "GstMessage"
  (mini-object (:struct gst-mini-object-cstruct))
  ;; (mini-object (g-boxed-foreign gst-mini-object))
  (type :int)
  (timestamp :uint64)
  (src :pointer)
  ;; (src (g-object gst-object))
  (seqnum :uint32))

(defcfun ("gst_is_video_overlay_prepare_window_handle_message" gst-is-video-overlay-prepare-window-handle-message) :boolean
  (message :pointer))

(export 'gst-is-video-overlay-prepare-window-handle-message)
